Repository cloudmesh/technologies, pull requests merged in 2018-11, with the labels that each got.

#486 wrong author: updated the references-fa18-523-70.bib file
  bib/references-fa18-523-70.bib
  chapters/tech/amqp.md
  chapters/tech/elasticsearch.md
  chapters/tech/rasdaman.md
  chapters/tech/voldemort.md
Labels: bibtex

#539 Update neptune.md
  chapters/tech/neptune.md
Labels: Review Comments not Integrated, Stalled

#538 Update redis.md
  chapters/tech/redis.md
Labels: Review Comments not Integrated, Stalled

#537 Update globus-online-gridftp.md
  chapters/tech/globus-online-gridftp.md
Labels: Review Comments not Integrated, Stalled

#536 Update rabbitmq.md
  chapters/tech/rabbitmq.md
Labels: Stalled, improve

#547 Create references-fa18-423-03.bib
  bib/references-fa18-423-03.bib
Labels: bibtex

#542 Update references-fa18-523-74.bib
  bib/references-fa18-523-74.bib
Labels: bibtex

#604 Pull Request
  bib/references-fa18-523-58.bib
  chapters/tech/apache-apex.md
  chapters/tech/atmosphere.md
  chapters/tech/dc.js.md
  chapters/tech/dryad.md
  chapters/tech/google-cloud-sql.md
  chapters/tech/openstack-heat.md
Labels: bibtex

#611 Corrected errors in bib file and modified tech summaries
  bib/references-fa18-523-66.bib
  chapters/tech/apache-derby.md
  chapters/tech/r.md
  chapters/tech/snort.md
  chapters/tech/taverna.md
Labels: conflict

#610 Update ibm-bluemix.md
  chapters/tech/ibm-bluemix.md
Labels: improve

#623 Latest changes/corrections
  bib/references-fa18-523-79.bib
  chapters/tech/lucene.md
  chapters/tech/winery.md
Labels: bibtex

#619 Update protobuf.md
  chapters/tech/protobuf.md
Labels: improve

#626 suggested changes for fa18-523-81
  bib/references-fa18-523-81.bib
  chapters/tech/apache-beam.md
  chapters/tech/apache-oodt.md
  chapters/tech/drill.md
  chapters/tech/hcatalog.md
  chapters/tech/hyper-v.md
  chapters/tech/yarn.md
Labels: bibtex

#636 Update references-fa18-523-59.bib
  bib/references-fa18-523-59.bib
Labels: bibtex

#627 Update graphlab.md
  chapters/tech/graphlab.md
Labels: failed

#629 Create references-fa18-423-05.bib
  bib/references-fa18-423-05.bib
Labels: bibtex

#515 Update bittorrent.md
  chapters/tech/bittorrent.md
Labels: Under Review
